# Rustfmt configuration
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
merge_derives = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
fn_call_width = 60 