name: Debian Package Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-deb:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Debian package
        run: cargo deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: target/debian/*.deb

  release:
    runs-on: ubuntu-24.04
    needs: build-deb
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: debian-package
          path: dist

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.deb"
          allowUpdates: true
          draft: false
          prerelease: false
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
